---
- name: define libvirt network
  virt_net:
    command: define
    name: "{{ item.netname }}"
    xml: "{{ lookup('template', 'bridge.xml.j2') }}"
  with_items: "{{ vmhost_network }}"

- name: start libvirt network
  virt_net:
    autostart: "yes"
    state: "active"
    name: "{{ item.netname }}"
  with_items: "{{ vmhost_network }}"