---
- name: Create ssh config directory if it does not exist
  ansible.builtin.file:
    path: "{{ mckadm_user_home }}/.ssh"
    state: directory
    mode: '0750'
    owner: mckadm

- name: Create disks directory if it does not exist
  ansible.builtin.file:
    path: "{{ disks_location }}"
    state: directory
    mode: '0750'

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "{{ mckadm_user_home }}/.ssh/id_ed25519"
    type: ed25519
