---
- name: Ensture user "{{ akvmadm_user }}" is created
  user:
    name: "{{ akvmadm_user }}"
    comment: Mini Cluster Kube Adm
    group: libvirt-qemu
    groups: kvm, libvirt
    shell: /bin/bash