---
- name: define libvirt network
  virt_net:
    command: define
    name: "host-bridge"
    xml: "{{ lookup('template', 'host-bridge.xml') }}"

- name: start libvirt network
  virt_net:
    autostart: "yes"
    state: "active"
    name: "host-bridge"
