---
vmhost_network:
    - netname: mck
      bridge_name: br-mck
      net4_address: '192.168.8.0/24'
      net4_dhcp: True

nodes:
    - name: mck-master1    
      cpu: 1
      mem: 768
      root_size: 10
      var_size: 20
      network: { name: mck, ip: 192.168.8.10 }
