---
vm_base:
  url: https://cloud-images.ubuntu.com/focal/20210129/focal-server-cloudimg-amd64-disk-kvm.img
  local_filename: 20210129_focal-server-cloudimg-amd64-disk-kvm.img
  sha256sum: d51376d03e19122f72fe9e0d520c37a09bb63ff160e4ba2c2b5af8a11da8647e

vmhost_network:
    - netname: mck
      bridge_name: br-mck
      net4_address: '192.168.8.0/24'
      net4_dhcp: True

nodes:
    - name: mck-master1    
      cpu: 1
      mem: 768
      root_size: 10
      var_size: 20
